In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("Social_Network_Ads.csv")
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
dataset = pd.get_dummies(dataset,drop_first=True)

In [4]:
dataset = dataset.drop("User ID",axis=1)

In [5]:
dataset.columns

Index(['Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [6]:
I = dataset [['Age', 'EstimatedSalary', 'Gender_Male']]
D = dataset [['Purchased']]

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(I,D,train_size=0.70,random_state=0)

In [9]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier

grid_param = {'criterion' : ['gini', 'entropy', 'log_loss'],'splitter':['best', 'random'],
              'max_features' :['auto', 'sqrt', 'log2']}

grid = GridSearchCV(DecisionTreeClassifier(), grid_param,verbose=3,refit=True,n_jobs=-1,scoring="f1_weighted")

grid.fit(x_train,y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning:
30 fits failed out of a total of 90.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
30 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 681, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 942, in fit
    X_idx_sorted=X_idx_sorted,
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 352, in fit
    criterion = CRITERIA_CLF[self.criterion](
KeyError: 'log_loss'

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:972: UserWarning: One or more of the test scores are non-finite: [0.85940678 0.81051923 0.82780964 0.81783208 0.83487479 0.85328202
 0.81359444 0.83316452 0.81568758 0.85749164 0.84633385 0.80255905
        nan        nan        nan        nan        nan        nan]
  category=UserWarning,

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=3)

In [10]:
y_pred = grid.predict(x_test)

In [11]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [12]:
from sklearn.metrics import classification_report
class_report = classification_report(y_test, y_pred)

In [17]:
re = grid.cv_results_

In [31]:
from sklearn.metrics import f1_score
f1=f1_score(y_test,y_pred,average='weighted')

print("Best parameter for detemining the score {}".format(f1),grid.best_params_,grid.best_score_)

Best parameter for detemining the score 0.874621476822735 {'criterion': 'gini', 'max_features': 'auto', 'splitter': 'best'} 0.8594067752364966

In [40]:
from sklearn.metrics import precision_score
pre=recall_score(y_test,y_pred,average='weighted')
pre

0.875

In [32]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

0.8581352269218895

In [33]:
cm

array([[72,  7],
       [ 8, 33]], dtype=int64)

In [28]:
x_test.shape

(120, 3)

In [34]:
print(class_report)

              precision    recall  f1-score   support

           0       0.90      0.91      0.91        79
           1       0.82      0.80      0.81        41

    accuracy                           0.88       120
   macro avg       0.86      0.86      0.86       120
weighted avg       0.87      0.88      0.87       120

In [27]:
table = pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.013930,0.003275,0.007508,0.001395,gini,auto,best,"{'criterion': 'gini', 'max_features': 'auto', ...",0.852966,0.799537,0.824293,0.928571,0.891667,0.859407,0.046224,1
1,0.014649,0.003273,0.007825,0.006869,gini,auto,random,"{'criterion': 'gini', 'max_features': 'auto', ...",0.835985,0.821429,0.737029,0.787433,0.870721,0.810519,0.045443,11
2,0.017603,0.006269,0.005817,0.003949,gini,sqrt,best,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.819142,0.782971,0.823129,0.841045,0.872761,0.827810,0.029337,7
3,0.013999,0.004501,0.005332,0.001006,gini,sqrt,random,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.874254,0.840114,0.733523,0.785714,0.855556,0.817832,0.051464,8
4,0.011322,0.002000,0.006360,0.001558,gini,log2,best,"{'criterion': 'gini', 'max_features': 'log2', ...",0.852966,0.799537,0.806153,0.822861,0.892857,0.834875,0.034372,5
5,0.008243,0.001289,0.004641,0.001241,gini,log2,random,"{'criterion': 'gini', 'max_features': 'log2', ...",0.872432,0.819142,0.807622,0.874356,0.892857,0.853282,0.033548,3
6,0.008805,0.001240,0.005520,0.001204,entropy,auto,best,"{'criterion': 'entropy', 'max_features': 'auto...",0.819142,0.821429,0.772092,0.804432,0.850877,0.813594,0.025646,10
7,0.008605,0.000837,0.005131,0.000765,entropy,auto,random,"{'criterion': 'entropy', 'max_features': 'auto...",0.875644,0.859435,0.787755,0.787433,0.855556,0.833165,0.037814,6
8,0.008316,0.001030,0.005000,0.000895,entropy,sqrt,best,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.775048,0.821429,0.789152,0.859025,0.833784,0.815688,0.030313,9
9,0.007207,0.001143,0.003472,0.001353,entropy,sqrt,random,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.857143,0.928571,0.769053,0.875548,0.857143,0.857492,0.051381,2
10,0.008755,0.001696,0.004116,0.002699,entropy,log2,best,"{'criterion': 'entropy', 'max_features': 'log2...",0.857143,0.802399,0.770909,0.911105,0.890114,0.846334,0.052627,4
11,0.008695,0.000920,0.004146,0.001218,entropy,log2,random,"{'criterion': 'entropy', 'max_features': 'log2...",0.802399,0.782971,0.806153,0.841045,0.780228,0.802559,0.021801,12
12,0.008567,0.001232,0.000000,0.000000,log_loss,auto,best,"{'criterion': 'log_loss', 'max_features': 'aut...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
13,0.006387,0.000826,0.000000,0.000000,log_loss,auto,random,"{'criterion': 'log_loss', 'max_features': 'aut...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,14
14,0.006746,0.001342,0.000000,0.000000,log_loss,sqrt,best,"{'criterion': 'log_loss', 'max_features': 'sqr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,15
15,0.007013,0.001497,0.000000,0.000000,log_loss,sqrt,random,"{'criterion': 'log_loss', 'max_features': 'sqr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,16
16,0.002459,0.001196,0.000000,0.000000,log_loss,log2,best,"{'criterion': 'log_loss', 'max_features': 'log...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
17,0.004284,0.001265,0.000000,0.000000,log_loss,log2,random,"{'criterion': 'log_loss', 'max_features': 'log...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,18